# Generated by Django 3.1.1 on 2020-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('calories_in', models.IntegerField()),
                ('exercise_time', models.IntegerField(null=True)),
                ('exercise_type', models.CharField(choices=[('C', 'Cardio'), ('ST', 'Strength'), ('O', 'Other')], max_length=20, null=True)),
                ('steps', models.IntegerField(null=True)),
                ('calories_out', models.IntegerField(null=True)),
            ],
        ),
    ]
