# Generated by Django 3.1.1 on 2020-09-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('calories_in', models.IntegerField()),
                ('exercise_time', models.IntegerField(null=True)),
                ('exercise_type', models.CharField(choices=[('C', 'Cardio'), ('ST', 'Strength'), ('O', 'Other')], max_length=20, null=True)),
                ('steps', models.IntegerField(null=True)),
                ('calories_out', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
