# Generated by Django 3.1.2 on 2020-10-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='exercise_time',
        ),
        migrations.RemoveField(
            model_name='log',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='steps',
        ),
    ]
