# Generated by Django 3.1.2 on 2020-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0003_auto_20201004_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activity_lvl',
            field=models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1, null=True),
        ),
    ]
