# Generated by Django 3.1.2 on 2020-10-10 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorietracker', '0003_auto_20201009_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('user', 'date')},
        ),
    ]
