# Generated by Django 3.1.2 on 2020-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0004_log_activity_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='goal_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
