# Generated by Django 3.1.2 on 2020-10-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorietracker', '0005_auto_20201011_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='unit_preference',
            field=models.CharField(blank=True, choices=[('I', 'Imperial (pounds, feet, inches etc.)'), ('M', 'Metric (kgs, meters, centimeters etc.)')], default='M', help_text='Display metric or imperial units on analytics page', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='MFPCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
