# Generated by Django 3.1.2 on 2020-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0005_setting_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
