# Generated by Django 3.1.2 on 2020-10-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='calories_out',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
