# Generated by Django 3.1.2 on 2020-10-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20201016_1657'),
        ('calorietracker', '0008_Configure_Site_Names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
