# Generated by Django 3.1.2 on 2020-10-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0009_auto_20201005_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='activity_lvl',
            field=models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], help_text='Estimate your relative activity level', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='calories_in',
            field=models.IntegerField(help_text='Total calories consumed'),
        ),
        migrations.AlterField(
            model_name='log',
            name='calories_out',
            field=models.IntegerField(blank=True, help_text='If you have a fitness tracker, total calories burned', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=models.FloatField(help_text='Try to weigh yourself at the same time every day'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='activity',
            field=models.CharField(blank=True, choices=[('1', 'Sedentary (little or no exercise)'), ('2', 'Lightly active (light exercise/sports 1-3 days/week)'), ('3', 'Moderatetely active (moderate exercise/sports 3-5 days/week)'), ('4', 'Very active (hard exercise/sports 6-7 days a week)'), ('5', 'Extra active (very hard exercise/sports & physical job or 2x training)')], help_text='Used to estimate your total daily energy expenditure until we have enough data to calculate it', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='goal',
            field=models.CharField(blank=True, choices=[('L', 'Lose'), ('M', 'Maintain'), ('G', 'Gain')], help_text='Do you want to lose, maintain, or gain weight?', max_length=1, null=True),
        ),
    ]
