# Generated by Django 3.1.3 on 2020-11-04 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0011_auto_20201103_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfpcredentials',
            name='mfp_autosync_startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 5, 1, 38, 49, 8486)),
        ),
        migrations.AlterField(
            model_name='setting',
            name='goal_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 1, 38, 49, 10067), null=True),
        ),
    ]
