# Generated by Django 3.1.3 on 2020-11-04 18:20

import calorietracker.base_models
import calorietracker.models
from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0012_auto_20201104_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=django_measurement.models.MeasurementField(measurement=calorietracker.base_models.Weight, null=True),
        ),
        migrations.AlterField(
            model_name='mfpcredentials',
            name='mfp_autosync_startdate',
            field=models.DateTimeField(blank=True, default=calorietracker.models.get_default_goal_mfp_autosync_startdate),
        ),
        migrations.AlterField(
            model_name='setting',
            name='goal_date',
            field=models.DateTimeField(blank=True, default=calorietracker.models.get_default_goal_date, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='goal_weight',
            field=django_measurement.models.MeasurementField(blank=True, default=calorietracker.base_models.Weight(kg=80), measurement=calorietracker.base_models.Weight, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='height',
            field=django_measurement.models.MeasurementField(blank=True, default=calorietracker.base_models.Distance(m=1.75), measurement=calorietracker.base_models.Distance, null=True),
        ),
    ]
