- name: Initial server setup
  hosts: all
  remote_user: root

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create new 'admin' user
      user:
        name: admin
        # password: admin # needs to be hashed if used
        groups: sudo
        append: yes
        createhome: yes

    - name: Adding ssh key to authorized ssh keys for 'admin' user
      authorized_key: user=admin key="{{ lookup('file', './ssh_keys/id_ed25519.pub') }}"

    - name: install epel-release for ufw
      # ufw is not in the standard repo but in epel
      yum:
        name: epel-release
        state: latest

    - name: install ufw
      yum:
        name: ufw
        state: latest

    - name: Allow everything and enable UFW
      # Later or manual configuration is assumed
      community.general.ufw:
        state: enabled
        policy: allow

    - name: Allow ufw SSH
      community.general.ufw:
        rule: allow

    - name: Set logging for ufw
      community.general.ufw:
        logging: 'on'


    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes
      notify:
        - restart ssh

    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
      notify:
       - restart ssh

  handlers:
  - name: restart ssh
    service:
     name=sshd
     state=restarted
